# Generated by Django 5.1.5 on 2025-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('shape', models.CharField(choices=[('square', 'Square'), ('circle', 'Circle')], default='square', max_length=250)),
                ('patern', models.CharField(choices=[('dots', 'Dots'), ('lines', 'Lines'), ('square', 'Square')], default='regular', max_length=250)),
                ('bg_color', models.CharField(default='#000000', max_length=250)),
                ('fg_color', models.CharField(default='#000000', max_length=250)),
                ('gradient', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_iamges/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
