# Generated by Django 5.1.5 on 2025-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_rename_shape_qrcode_border_qrcode_border_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='patern',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='patterns',
            field=models.CharField(choices=[('dots', 'Dots'), ('lines', 'Lines'), ('square', 'Square')], default='square', max_length=250),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='bg_color',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='fg_color',
            field=models.CharField(default='', max_length=250),
        ),
    ]
