# Generated by Django 5.1.5 on 2025-03-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_remove_qrcode_patern_qrcode_patterns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='user',
        ),
    ]
