# Generated by Django 5.1.5 on 2025-03-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_remove_qrcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='time',
        ),
    ]
