# Generated by Django 5.1.5 on 2025-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_remove_qrcode_image_remove_qrcode_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='gradient',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
