# Generated by Django 5.1.5 on 2025-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0006_remove_qrcode_gradient_qrcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='border_width',
        ),
    ]
