# Generated by Django 5.1.5 on 2025-03-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_remove_qrcode_border_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='border',
        ),
    ]
