# Generated by Django 5.1.5 on 2025-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0009_qrcode_border_width_alter_qrcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
