# Generated by Django 5.1.5 on 2025-03-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0010_qrcode_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code_image',
        ),
    ]
