# Generated by Django 5.1.5 on 2025-03-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_userregister_email_alter_userregister_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
